import { Routes } from '@angular/router';
import { LandingComponent } from './features/auth/landing/landing.component';
import { RegisterComponent } from './features/auth/register/register.component';
import { OnboardingComponent } from './features/onboarding/onboarding.component';
import { DashboardComponent } from './features/dashboard/dashboard.component';
import { ActiveWorkoutComponent } from './features/workout/active-workout/active-workout.component';
import { WorkoutSummaryComponent } from './features/workout/workout-summary/workout-summary.component';
import { ProfileComponent } from './features/profile/profile.component';
import { ExerciseListComponent } from './features/exercises/exercise-list/exercise-list.component';
import { ExerciseCreateComponent } from './features/exercises/exercise-create/exercise-create.component';
import { ExerciseDetailComponent } from './features/exercises/exercise-detail/exercise-detail.component';
import { MeasurementListComponent } from './features/measurements/measurement-list/measurement-list.component';
import { MeasurementAddComponent } from './features/measurements/measurement-add/measurement-add.component';
import { ProfileEditComponent } from './features/profile/profile-edit/profile-edit.component';
import { SettingsComponent } from './features/settings/settings.component';
import { AccountComponent } from './features/settings/account/account.component';
import { ChangeEmailComponent } from './features/settings/account/change-email/change-email.component';
import { ChangePasswordComponent } from './features/settings/account/change-password/change-password.component';
import { RoutineCreateComponent } from './features/routines/routine-create/routine-create.component';
import { WorkoutDetailComponent } from './features/history/workout-detail/workout-detail.component';

export const routes: Routes = [
  { path: '', component: LandingComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'onboarding', component: OnboardingComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'tracker', component: ActiveWorkoutComponent },
  { path: 'tracker/summary', component: WorkoutSummaryComponent },
  { path: 'routines/create', component: RoutineCreateComponent },
  { path: 'routines/create/:id', component: RoutineCreateComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'profile/edit', component: ProfileEditComponent },
  { path: 'settings', component: SettingsComponent },
  { path: 'settings/account', component: AccountComponent },
  { path: 'settings/account/email', component: ChangeEmailComponent },
  { path: 'settings/account/password', component: ChangePasswordComponent },
  { path: 'exercises', component: ExerciseListComponent },
  { path: 'exercises/create', component: ExerciseCreateComponent },
  { path: 'exercises/:id', component: ExerciseDetailComponent },
  { path: 'measurements', component: MeasurementListComponent },
  { path: 'measurements/add', component: MeasurementAddComponent },
  { path: 'measurements/:id', component: MeasurementAddComponent },
  { path: 'history/:id', component: WorkoutDetailComponent },
  // Redirección por defecto (opcional, pero recomendada)
  { path: '**', redirectTo: '' }
];